"""add dist

Revision ID: 5022ceebd90d
Revises: ee2f3bd374e3
Create Date: 2020-04-02 23:24:25.772082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5022ceebd90d'
down_revision = 'ee2f3bd374e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fillup', sa.Column('dist', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fillup', 'dist')
    # ### end Alembic commands ###
