"""favourite vehicle

Revision ID: 94b733c58c61
Revises: ee2f3bd374e3
Create Date: 2020-04-13 22:52:59.085301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b733c58c61'
down_revision = 'ee2f3bd374e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fillup_vehicle_id'), 'fillup', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    with op.batch_alter_table('vehicle') as batch_op:
        batch_op.add_column(sa.Column('is_favourite', sa.Boolean(), nullable=True))
    op.create_index('idx_unq_fav_vehicle', 'vehicle', ['owner_id', 'is_favourite'], unique=True, sqlite_where=sa.text('is_favourite > 0'), postgresql_where=sa.text('is_favourite > 0'))
    op.create_index(op.f('ix_vehicle_owner_id'), 'vehicle', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_owner_id'), table_name='vehicle')
    op.drop_index('idx_unq_fav_vehicle', table_name='vehicle')
    with op.batch_alter_table('vehicle') as batch_op:
        batch_op.drop_column('is_favourite')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_fillup_vehicle_id'), table_name='fillup')
    # ### end Alembic commands ###
