"""user tokens

Revision ID: af546a7f2940
Revises: 66c980e57222
Create Date: 2021-02-21 17:51:04.534358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af546a7f2940"
down_revision = "66c980e57222"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("api_token", sa.String(length=32), nullable=True))
    op.add_column(
        "user", sa.Column("api_token_expiration", sa.DateTime(), nullable=True)
    )
    op.create_index(op.f("ix_user_api_token"), "user", ["api_token"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_index(op.f("ix_user_api_token"))
        batch_op.drop_column("api_token_expiration")
        batch_op.drop_column("api_token")
    # ### end Alembic commands ###
